//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        public long userID { get; set; }
        [Required(ErrorMessage ="This field is Required.")]
        [DisplayName("User Name")]
        public string userName { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Password")]
        public string password { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string confirmPassword { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("First Name")]
        public string fName { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Last Name")]
        public string lName { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Email ID")]
        public string email { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Phone Number")]
        public string phone { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Street Name")]
        public string street { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("City")]
        public string city { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Province")]
        public string province { get; set; }

        [Required(ErrorMessage = "This field is Required.")]
        [DisplayName("Country")]
        public string country { get; set; }
    }
}
